<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Building;

class BuildingSeeder extends Seeder
{
    public function run(): void
    {
        $buildings = [
            [
                'system_building_id' => 'BLD-001',
                'sio' => 'SIO-1001',
                'building_name' => 'Nirvana Tower A',
                'address_1' => '123 Business Street',
                'city' => 'New York',
                'zip_code' => '10001',
                'country' => 'USA',
                'clli' => 'NYCMNY12',
                'building_type' => 'Commercial',
                'building_rentable_area' => '50000',
                'building_measure_units' => 'SQFT',
                'latitude' => '40.7128',
                'longitude' => '-74.0060',
                'building_status' => 'Active',
                'purchase_price' => '15000000',
                'currency_type' => 'USD',
                'construction_year' => '2010',
                'portfolio' => 'Portfolio A',
                'portfolio_sub_group' => 'Group 1',
                'ownership_type' => 'Owned',
                'managed_by' => 'Nirvana Properties',
            ],
            [
                'system_building_id' => 'BLD-002',
                'sio' => 'SIO-1002',
                'building_name' => 'Nirvana Tower B',
                'address_1' => '456 Corporate Ave',
                'city' => 'Chicago',
                'zip_code' => '60601',
                'country' => 'USA',
                'clli' => 'CHCGIL01',
                'building_type' => 'Commercial',
                'building_rentable_area' => '42000',
                'building_measure_units' => 'SQFT',
                'latitude' => '41.8781',
                'longitude' => '-87.6298',
                'building_status' => 'Active',
                'purchase_price' => '12000000',
                'currency_type' => 'USD',
                'construction_year' => '2012',
                'portfolio' => 'Portfolio A',
                'portfolio_sub_group' => 'Group 2',
                'ownership_type' => 'Owned',
                'managed_by' => 'Nirvana Properties',
            ],
            [
                'system_building_id' => 'BLD-003',
                'sio' => 'SIO-1003',
                'building_name' => 'Nirvana Plaza',
                'address_1' => '789 Market Road',
                'city' => 'San Francisco',
                'zip_code' => '94103',
                'country' => 'USA',
                'clli' => 'SNFRCAXX',
                'building_type' => 'Mixed Use',
                'building_rentable_area' => '60000',
                'building_measure_units' => 'SQFT',
                'latitude' => '37.7749',
                'longitude' => '-122.4194',
                'building_status' => 'Active',
                'purchase_price' => '20000000',
                'currency_type' => 'USD',
                'construction_year' => '2015',
                'portfolio' => 'Portfolio B',
                'portfolio_sub_group' => 'Group 1',
                'ownership_type' => 'Owned',
                'managed_by' => 'Nirvana Properties',
            ],
            [
                'system_building_id' => 'BLD-004',
                'sio' => 'SIO-1004',
                'building_name' => 'Nirvana Center',
                'address_1' => '12 Finance Blvd',
                'city' => 'London',
                'zip_code' => 'EC1A',
                'country' => 'UK',
                'clli' => 'LNDNGB01',
                'building_type' => 'Commercial',
                'building_rentable_area' => '55000',
                'building_measure_units' => 'SQFT',
                'latitude' => '51.5074',
                'longitude' => '-0.1278',
                'building_status' => 'Active',
                'purchase_price' => '18000000',
                'currency_type' => 'GBP',
                'construction_year' => '2011',
                'portfolio' => 'Portfolio C',
                'portfolio_sub_group' => 'Group 3',
                'ownership_type' => 'Owned',
                'managed_by' => 'Nirvana UK',
            ],
            [
                'system_building_id' => 'BLD-005',
                'sio' => 'SIO-1005',
                'building_name' => 'Nirvana Tech Park',
                'address_1' => '88 Innovation Drive',
                'city' => 'Bangalore',
                'zip_code' => '560001',
                'country' => 'India',
                'clli' => 'BLRIND01',
                'building_type' => 'IT Park',
                'building_rentable_area' => '80000',
                'building_measure_units' => 'SQFT',
                'latitude' => '12.9716',
                'longitude' => '77.5946',
                'building_status' => 'Active',
                'purchase_price' => '9000000',
                'currency_type' => 'INR',
                'construction_year' => '2018',
                'portfolio' => 'Portfolio D',
                'portfolio_sub_group' => 'Group 4',
                'ownership_type' => 'Owned',
                'managed_by' => 'Nirvana India',
            ],
        ];

        foreach ($buildings as $building) {
            Building::create($building);
        }
    }
}
